### ISSUE TITLE
提示缺少qbee 依赖，如何解决?

### ISSUE THREAD

**Issue by ashesofdream** [hyy-666/luci-app-qBittorrent-enhanced#1]

**Comment by ashesofdream** [comment]
才发现在其它仓库....抱歉

**Comment by solarflows** [comment]
可以换luci的仓库，里面的qbee修好了，这个有点问题，因为配置文件配置节点相同，会导致匹配失败，然后配置文件没法从luci界面同步到qb中，天灵大佬的仓库里也有一个包，你可以去看看

**Comment by solarflows** [comment]
qbee的意义不大，除非你有非常大的内存，不然很容易崩，不知道是openwrt的问题还是qbee的问题，我现在没在用这个东西了，可能会有奇怪的bug😂
